import torch
import torch.nn.functional as F #contains standalone nn funct, used for softmax

torch.manual_seed(42) #makes the random numbers generated by torch.rand() reproducible
seq_len = 4 #no of tokens in i/p sentence
d_model = 8 #dimensionality of the input embeddings

x = torch.randn(seq_len, d_model)
print("Input embeddings x:", x.shape)

d_k = 8 #size of query and key vectors

W_q = torch.rand(d_model, d_k) #weight matrix for query
W_k = torch.rand(d_model, d_k) #weight matrix for key
W_v = torch.rand(d_model, d_k) #weight matrix for value

Q = x @ W_q #query matrix @ is for matrix multiplication
K = x @ W_k #key matrix
V = x @ W_v #value matrix
# every token now has a become a query. key and value vector

print("Q shape",Q.shape)
print("K shape",K.shape)
print("V shape",V.shape)

scores = Q @ K.T
print("Raw scores shape:", scores.shape)
print("Raw scores:", scores)

scores_scaled = scores / (d_k**0.5) #scaling is done as dot products become huge when dimensions increase, and large no make softmax unstable
print("Scaled scores:", scores_scaled)

#softmax on attn scores (each row sums to 1)
attn_weights = F.softmax(scores_scaled, dim=-1)
print("\nAttention weights:", attn_weights)
print("Row sums (should be 1):", attn_weights.sum(dim=-1))

output = attn_weights @ V #each token's representation has been updated using info from other tokens acc to learned attention
print("Output shape:", output.shape)
print("Output:", output)

assert output.shape == x.shape
print("Output shape matches input shape!")